apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ (print .Values.service.name "-config") | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.service.name | quote }}
    app.kubernetes.io/part-of: {{ .Values.service.name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  namespace: {{ .Values.namespace | quote }}
data:
{{ toYaml .Values.configMap.content | indent 4 }}