apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 annotations:
 name: {{ (print .Values.service.name "-hpa") | quote }}
 namespace: {{ .Values.namespace }}
 labels:
   app: {{ .Values.service.name | quote }}
   chart: {{ .Values.service.name | quote }}
   heritage: {{ .Release.Service }}
   release: {{ .Release.Name }}
spec:
 maxReplicas: 5
 minReplicas: 2
 targetCPUUtilizationPercentage: 70
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ .Values.service.name }}