apiVersion: v1
kind: Service
metadata:
 name: {{ .Values.service.name }}
 namespace: {{ .Values.namespace }}
 labels:
   app.kubernetes.io/name: {{ .Values.service.name | quote }}
   app.kubernetes.io/part-of: {{ .Values.service.name | quote }}
   app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
   app: {{ .Values.service.name }}
   chart: {{ .Values.service.name }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.service.name }}
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ .Values.service.name }}
