apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
 name: {{ .Values.service.name }}
 namespace: {{ .Values.namespace }}
 labels:
   app: {{ .Values.service.name }}
   app.kubernetes.io/name: {{ .Values.service.name | quote }}
   app.kubernetes.io/part-of: {{ .Values.system | quote }}
   app.kubernetes.io/managed-by: {{ .Release.Service | quote }}  
spec:
    gateways:
    - {{ .Values.ingress.gateWayName | quote }}
    hosts:
    - {{ .Values.ingress.host | quote }}
    http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: {{ (print .Values.service.name "." .Values.namespace ".svc.cluster.local") | quote }}
          port:
            number: 80